export const SELECT_MOVIE_LIST = "SELECT_MOVIE_LIST";
export const GET_MOVIES = "GET_MOVIES";
export const FETCH_MOVIES = "FETCH_MOVIES";
export const FETCH_MOVIE_DETAILS = "FETCH_MOVIE_DETAILS";
export const GET_MOVIE_DETAILS = "GET_MOVIE_DETAILS";
export const SELECT_MOVIE_ID = "SELECT_MOVIE_ID";
